### ISSUE TITLE
Tadiran Wind P65 constantly turns off

### ISSUE THREAD

**Issue by Fannangir** [make-all/tuya-local#237]
Hi,
Since update to revision 0.19, the AC constantly turns off after a few seconds following on from the remote control or the cloud application.
Returned back to revision 0.18.2, the issue does not appear.

another thing I have noticed is that the device becomes unavailable very often, again only in revision 0.19. Revision 0.18.2 works well.

**Comment by make-all** [comment]
Thanks for the report. I"ve marked 0.19.0 as a beta until the issue can be figured out.

**Comment by make-all** [comment]
I have released 0.19.1 with the changes previously made for #195 reverted.  I think this is the most likely cause of the problem, based on information here and on #238, and I think I reproduced the problem on 0.19.0 with one of my devices, but the same steps work OK on 0.19.1.  Please let me know if 0.19.1 is working OK for you.

**Comment by Fannangir** [comment]
Just updated.
Unfortunately the same issue, as soon as the device turns on, it turns back off after 10-20 seconds.

**Comment by make-all** [comment]
Please try updating to the latest "main".  I reverted the tinytuya library version in this one.

**Comment by Fannangir** [comment]
Just updated.
Works fine for about 10 mins, seems promising.

**Comment by make-all** [comment]
OK, I've released 0.19.2 now with the library reverted, the 3.2 support removed (as it depended on the new library) and the retry count increased to make recovery more likely (mainly this was probably an issue with the extra protocol version to try).

**Comment by Fannangir** [comment]
Thank you very much.
Updated, seems to work as it was in 0.18.xx.

**Comment by Fannangir** [comment]
Hi,
The issue has returned with the latest update to 0.20.
Seems like the update does not solve the issue completely.

**Comment by Fannangir** [comment]
@make-all, should I open a new issue?

**Comment by make-all** [comment]
no need, I will reopen this one.  It does not seem that this is related to the general instability of the 1.6.6 tinytuya library, so will need more investigation. Could you please download the diagnostics for the device on the Settings/Devices page, and post here.

**Comment by Fannangir** [comment]
Hi,
Thank you very much for your support.
Actually, it is working OK for two days following restart of the host.
I am attaching the log anyway, maybe it could be helpful to find the cause.
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.10.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Asia/Jerusalem",
    "os_name": "Linux",
    "os_version": "5.15.72",
    "supervisor": "2022.10.0",
    "host_os": "Home Assistant OS 9.2",
    "docker_version": "20.10.17",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "smartthinq_sensors": {
      "version": "0.24.2",
      "requirements": [
        "pycountry>=20.7.3",
        "xmltodict>=0.12.0",
        "cchardet>=2.1.7"
      ]
    },
    "sonoff": {
      "version": "3.3.1",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "nuki_ng": {
      "version": "0.2.1",
      "requirements": []
    },
    "adaptive_lighting": {
      "version": "1.1.0",
      "requirements": []
    },
    "mass": {
      "version": "2022.8.4",
      "requirements": [
        "music-assistant==1.8.7"
      ]
    },
    "powercalc": {
      "version": "v0.26.1",
      "requirements": [
        "numpy>=1.21.1"
      ]
    },
    "citymind_water_meter": {
      "version": "2.0.2",
      "requirements": []
    },
    "circadian_lighting": {
      "version": "2.1.3",
      "requirements": []
    },
    "hacs": {
      "version": "1.28.3",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "alarmo": {
      "version": "v1.9.6",
      "requirements": []
    },
    "xiaomi_cloud_map_extractor": {
      "version": "v2.2.0",
      "requirements": [
        "pillow",
        "pybase64",
        "python-miio",
        "requests",
        "pycryptodome"
      ]
    },
    "ramzor_sensor": {
      "version": "0.1.0",
      "requirements": []
    },
    "scheduler": {
      "version": "v0.0.0",
      "requirements": []
    },
    "webrtc": {
      "version": "v2.3.1",
      "requirements": []
    },
    "ui_lovelace_minimalist": {
      "version": "v1.1.5",
      "requirements": [
        "aiofiles==0.8.0",
        "aiogithubapi>=22.2.4"
      ]
    },
    "browser_mod": {
      "version": "2.1.2",
      "requirements": []
    },
    "hebcal": {
      "version": "2.0.8",
      "requirements": []
    },
    "localtuya": {
      "version": "4.1.1",
      "requirements": []
    },
    "iphonedetect": {
      "version": "1.4.0",
      "requirements": []
    },
    "simpleicons": {
      "version": "v2.2.0",
      "requirements": [
        "simpleicons==7.14.0"
      ]
    },
    "reolink_dev": {
      "version": "0.57",
      "requirements": [
        "reolink==0.0.62"
      ]
    },
    "ytube_music_player": {
      "version": "20220205.01",
      "requirements": [
        "ytmusicapi==0.19.5",
        "pytube==10.5.1",
        "integrationhelper==0.2.2"
      ]
    },
    "miwifi": {
      "version": "2.8.2",
      "requirements": []
    },
    "tuya_local": {
      "version": "0.20.0",
      "requirements": [
        "pycryptodome~=3.15.0",
        "tinytuya==1.7.1"
      ]
    },
    "smartir": {
      "version": "1.17.6",
      "requirements": [
        "aiofiles==0.6.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya_local",
    "iot_class": "local_polling",
    "name": "Tuya Local",
    "version": "0.20.0",
    "documentation": "https://github.com/make-all/tuya-local",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "dependencies": [],
    "codeowners": [
      "@make-all"
    ],
    "requirements": [
      "pycryptodome~=3.15.0",
      "tinytuya==1.7.1"
    ],
    "config_flow": true,
    "is_built_in": false
  },
  "data": {
    "name": "Tadiran Air Conditioner",
    "type": "tadiran_wind_heatpump",
    "device_id": "**REDACTED**",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "api_version": 3.3,
    "status": {},
    "cached_state": {
      "1": false,
      "2": 26,
      "3": 260,
      "4": "cooling",
      "5": "low",
      "101": 0,
      "102": 260,
      "103": 255,
      "104": "stop",
      "105": "stop",
      "106": -300,
      "107": false,
      "108": false,
      "updated_at": 1666641281.3008862
    },
    "pending_state": {},
    "home_assistant": {
      "name": "Tadiran Air Conditioner",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "climate.tadiran_air_conditioner",
            "state": "off",
            "attributes": {
              "hvac_modes": [
                "cool",
                "dry",
                "heat_cool",
                "off",
                "heat",
                "fan_only"
              ],
              "min_temp": 16,
              "max_temp": 32,
              "target_temp_step": 1.0,
              "fan_modes": [
                "auto",
                "low",
                "medium",
                "high"
              ],
              "current_temperature": 26.0,
              "temperature": 26,
              "fan_mode": "low",
              "unknown_101": 0,
              "unknown_102": 260,
              "unknown_103": 255,
              "unknown_104": "stop",
              "unknown_105": "stop",
              "unknown_106": -300,
              "unknown_107": false,
              "unknown_108": false,
              "icon": "mdi:hvac-off",
              "friendly_name": "Tadiran Air Conditioner",
              "supported_features": 9
            },
            "last_changed": "2022-10-23T19:07:35.833743+00:00",
            "last_updated": "2022-10-24T17:03:40.629977+00:00"
          }
        }
      ]
    }
  }
}
