### ISSUE TITLE
Multiple thermostats Beok TGR81

### ISSUE THREAD

**Issue by SellSan** [make-all/tuya-local#591]
**Describe the bug**
I have 9 pcs Beok TGR81 thermostats in my house connected to WiFi network. I have added all of them but experiencing Unavalible status for some of them. The Unavalible status of thermostats entities vary betwene thermostats. Sometimes more of them is avalible sometime less.

**To Reproduce**
I don't know how to reproduce this behavior. The adding process was succesfull without problems. When I was changing the Entities names they appeard avalible.

**Expected behavior**
All 9 Thermostats and their Entities should be all the time avalible.

**Additional context**
Its not a context, but when I want to change the set temperature from, for example, 23 to 22 degrees in Home Assistant I can do it, the temperature is changed on the physical thermostat, but just after the chage the indicator of thermostat is going bac to the old vale (23) but on physical thermostat the value is changed (22).

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.3.6",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Warsaw",
    "os_name": "Linux",
    "os_version": "5.15.90",
    "supervisor": "2023.03.3",
    "host_os": "Home Assistant OS 9.5",
    "docker_version": "20.10.22",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "presence_simulation": {
      "version": "2.4",
      "requirements": []
    },
    "hacs": {
      "version": "1.31.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "average": {
      "version": "2.3.0",
      "requirements": []
    },
    "tuya_local": {
      "version": "2022.3.1",
      "requirements": [
        "pycryptodome~=3.17",
        "tinytuya==1.12.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "@make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "requirements": [
      "pycryptodome~=3.17",
      "tinytuya==1.12.0"
    ],
    "version": "2022.3.1",
    "is_built_in": false
  },
  "data": {
    "name": "Termostat pok\u00f3j nad gara\u017cem",
    "type": "beok_tgr81_thermostat_c",
    "device_id": "**REDACTED**",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": "auto",
    "api_version_set": 3.2,
    "api_version_used": 3.2,
    "api_working": true,
    "status": {
      "1": true,
      "2": "manual",
      "10": true,
      "16": 24,
      "19": 32,
      "24": 210,
      "27": -2,
      "101": 1,
      "102": "52"
    },
    "cached_state": {
      "updated_at": 1680480092.7124414,
      "1": true,
      "2": "manual",
      "10": true,
      "16": 24,
      "19": 32,
      "24": 210,
      "27": -2,
      "101": 1,
      "102": "52"
    },
    "pending_state": {},
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "Termostat pok\u00f3j nad gara\u017cem",
      "name_by_user": "Termostat pok\u00f3j nad gara\u017cem",
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "climate.termostat_pokoj_nad_garazem",
            "state": "unavailable",
            "attributes": {
              "hvac_modes": [
                "off",
                "heat"
              ],
              "min_temp": null,
              "max_temp": null,
              "target_temp_step": 1.0,
              "preset_modes": [
                "Schedule",
                "Manual"
              ],
              "friendly_name": "Termostat pok\u00f3j nad gara\u017cem",
              "supported_features": 17
            },
            "last_changed": "2023-04-03T00:01:30.650108+00:00",
            "last_updated": "2023-04-03T00:01:30.650108+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "switch",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.termostat_pokoj_nad_garazem_anti_frost",
            "state": "unavailable",
            "attributes": {
              "device_class": "switch",
              "icon": "mdi:snowflake-melt",
              "friendly_name": "Termostat pok\u00f3j nad gara\u017cem Anti-frost"
            },
            "last_changed": "2023-04-03T00:01:30.652723+00:00",
            "last_updated": "2023-04-03T00:01:30.652723+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": "\u00b0C",
          "state": {
            "entity_id": "number.termostat_pokoj_nad_garazem_calibration_offset",
            "state": "-2",
            "attributes": {
              "min": -9,
              "max": 9,
              "step": 1.0,
              "mode": "auto",
              "unit_of_measurement": "\u00b0C",
              "icon": "mdi:thermometer",
              "friendly_name": "Termostat pok\u00f3j nad gara\u017cem Calibration offset"
            },
            "last_changed": "2023-04-03T00:01:32.713815+00:00",
            "last_updated": "2023-04-03T00:01:32.713815+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "lock.termostat_pokoj_nad_garazem_child_lock",
            "state": "unavailable",
            "attributes": {
              "friendly_name": "Termostat pok\u00f3j nad gara\u017cem Child lock",
              "supported_features": 0
            },
            "last_changed": "2023-04-03T00:01:30.651073+00:00",
            "last_updated": "2023-04-03T00:01:30.651073+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "problem",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "binary_sensor.termostat_pokoj_nad_garazem_error",
            "state": "on",
            "attributes": {
              "device_class": "problem",
              "friendly_name": "Termostat pok\u00f3j nad gara\u017cem Error"
            },
            "last_changed": "2023-04-03T00:01:32.712808+00:00",
            "last_updated": "2023-04-03T00:01:32.712808+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "temperature",
          "icon": null,
          "unit_of_measurement": "\u00b0C",
          "state": {
            "entity_id": "number.termostat_pokoj_nad_garazem_high_temperature_limit",
            "state": "32",
            "attributes": {
              "min": 30,
              "max": 90,
              "step": 1.0,
              "mode": "auto",
              "unit_of_measurement": "\u00b0C",
              "device_class": "temperature",
              "icon": "mdi:thermometer-chevron-up",
              "friendly_name": "Termostat pok\u00f3j nad gara\u017cem High temperature limit"
            },
            "last_changed": "2023-04-03T00:01:32.714697+00:00",
            "last_updated": "2023-04-03T00:01:32.714697+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": "\u00b0C",
          "state": {
            "entity_id": "number.termostat_pokoj_nad_garazem_hysteresis_3",
            "state": "1",
            "attributes": {
              "min": 1,
              "max": 5,
              "step": 1.0,
              "mode": "auto",
              "unit_of_measurement": "\u00b0C",
              "icon": "mdi:arrow-expand-vertical",
              "friendly_name": "Termostat pok\u00f3j nad gara\u017cem Hysteresis"
            },
            "last_changed": "2023-04-03T00:01:32.716234+00:00",
            "last_updated": "2023-04-03T00:01:32.716234+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "temperature",
          "icon": null,
          "unit_of_measurement": "\u00b0C",
          "state": {
            "entity_id": "number.termostat_pokoj_nad_garazem_low_temperature_limit_3",
            "state": "unknown",
            "attributes": {
              "min": 5,
              "max": 20,
              "step": 1.0,
              "mode": "auto",
              "unit_of_measurement": "\u00b0C",
              "device_class": "temperature",
              "icon": "mdi:thermometer-chevron-down",
              "friendly_name": "Termostat pok\u00f3j nad gara\u017cem Low temperature limit"
            },
            "last_changed": "2023-04-03T00:01:32.715483+00:00",
            "last_updated": "2023-04-03T00:01:32.715483+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "restart",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "button.termostat_pokoj_nad_garazem_reset_3",
            "state": "unavailable",
            "attributes": {
              "device_class": "restart",
              "friendly_name": "Termostat pok\u00f3j nad gara\u017cem Reset"
            },
            "last_changed": "2023-04-03T00:01:30.651899+00:00",
            "last_updated": "2023-04-03T00:01:30.651899+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "select.termostat_pokoj_nad_garazem_sensor_selection_3",
            "state": "unknown",
            "attributes": {
              "options": [
                "Internal",
                "Both",
                "External"
              ],
              "friendly_name": "Termostat pok\u00f3j nad gara\u017cem Sensor selection"
            },
            "last_changed": "2023-04-03T00:01:32.716848+00:00",
            "last_updated": "2023-04-03T00:01:32.716848+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "select.termostat_pokoj_nad_garazem_working_week_3",
            "state": "unavailable",
            "attributes": {
              "options": [
                "Off",
                "5 days",
                "6 days",
                "7 days"
              ],
              "icon": "mdi:calendar-clock",
              "friendly_name": "Working week"
            },
            "last_changed": "2023-04-03T00:01:07.325464+00:00",
            "last_updated": "2023-04-03T00:01:07.325464+00:00"
          }
        }
      ]
    }
  }
}

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

This error originated from a custom integration.

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:184
Integration: Tuya Local (documentation, issues)
First occurred: 1:44:15 PM (26 occurrences)
Last logged: 2:48:43 PM

Failed to refresh device state for Lampa salon
Lampka sypialnia error reading: Unexpected Payload from Device
Failed to refresh device state for Lampka sypialnia
Lampa salon error reading: Unexpected Payload from Device

https://user-images.githubusercontent.com/121897721/229567378-b48279fe-ebc0-44e4-8a5c-c71aa4e2d12f.mp4

![image](https://user-images.githubusercontent.com/121897721/229567020-e56ecd8a-c174-45da-a795-015f0e16e841.png)

**Comment by elninosi** [comment]
I can confirm the same behavior.

**Comment by Nikolay-Ch** [comment]
May be this issue is related to another? #653

**Comment by make-all** [comment]
Yes, probably

**Comment by make-all** [comment]
As #653 is fixed in 2023.5.1, please confirm if this bug still exists in the case where there are many devices.

**Comment by make-all** [comment]
Assuming the issue is fixed, as no feedback was received.

**Comment by SellSan** [comment]
Hi Jason, i did not have time to have a look in to this since then. If issue still persist I will raise defect again.

Greetings 

⁣Pobierz aplikację BlueMail dla systemu Android ​

W dniu 11 cze 2023, 17:22, o 17:22, użytkownik Jason Rumney ***@***.***> napisał:
